
import Header from '../components/Header'

import Footer from '../components/Footer'
import Head from 'next/head'


function Layout ({children}) {
  return (
    <div>  
       <Head>
        <title>my-App Home </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {children} 
      
    </div>
  )
}

export default Layout